"use strict";
const test=require("node:test");const assert=require("node:assert/strict");
const {splitApps,groupApps,filterUsers,formatAmount,formatKoreanNumber,formatAdjustmentPreview,formatRelativeTime,MAX_ADJUSTMENT_AMOUNT}=require("../renderer/ui-logic");
const {SdAdminApi,MAX_ADJUSTMENT_AMOUNT:API_MAX_ADJUSTMENT_AMOUNT}=require("../lib/sd-admin-api");const {PresenceReporter}=require("../integration/presence-reporter");
const BASE="https://example.supabase.co",KEY="sb_publishable_abcdefghijklmnopqrstuvwxyz";
function jsonResponse(status,body){return{ok:status>=200&&status<300,status,text:async()=>body==null?"":JSON.stringify(body)};}
test("+N UI: first 3 apps and remaining count are stable",()=>{const apps=["a","b","c","d","e"].map(id=>({app_id:id,app_name:id.toUpperCase(),instance_id:id}));const collapsed=splitApps(apps,false,3);assert.equal(collapsed.visible.length,3);assert.equal(collapsed.hiddenCount,2);assert.equal(collapsed.total,5);const expanded=splitApps(apps,true,3);assert.equal(expanded.visible.length,5);assert.equal(expanded.hiddenCount,0);});
test("duplicate instances group under one app and preserve count",()=>{const grouped=groupApps([{app_id:"logistics",app_name:"물류센터",instance_id:"1",last_seen_at:"2026-08-22T00:00:00Z"},{app_id:"logistics",app_name:"물류센터",instance_id:"2",last_seen_at:"2026-08-22T00:01:00Z"},{app_id:"center",app_name:"종합센터",instance_id:"3",last_seen_at:"2026-08-22T00:02:00Z"}]);const logistics=grouped.find(x=>x.appId==="logistics");assert.equal(grouped.length,2);assert.equal(logistics.count,2);assert.equal(logistics.instances.length,2);});
test("user filters do not lose offline users unless explicitly requested",()=>{const users=[{nickname:"Alpha",account_number:"SD-001",online:true},{nickname:"Beta",account_number:"SD-002",online:false}];assert.equal(filterUsers(users,"",false).length,2);assert.equal(filterUsers(users,"",true).length,1);assert.equal(filterUsers(users,"002",false)[0].nickname,"Beta");});
test("amount and relative-time formatting are deterministic",()=>{assert.equal(formatAmount(1234567),"1,234,567 SD");assert.equal(formatAmount(-500),"-500 SD");const now=Date.parse("2026-08-22T01:00:00Z");assert.equal(formatRelativeTime("2026-08-22T00:59:30Z",now),"30초 전");assert.equal(formatRelativeTime("2026-08-22T00:50:00Z",now),"10분 전");});
test("amount preview reads Korean units through 1000억",()=>{assert.equal(MAX_ADJUSTMENT_AMOUNT,100000000000);assert.equal(API_MAX_ADJUSTMENT_AMOUNT,MAX_ADJUSTMENT_AMOUNT);assert.equal(formatKoreanNumber(100000),"십만");assert.equal(formatKoreanNumber(10000000000),"백억");assert.equal(formatKoreanNumber(100000000000),"천억");assert.equal(formatAdjustmentPreview(100000),"100,000 SD (십만)");assert.equal(formatAdjustmentPreview(10000000000),"10,000,000,000 SD (백억)");});
test("wallet adjustment accepts exact 1000억 and sends idempotency request id unchanged",async()=>{const calls=[];const fetchImpl=async(url,options)=>{calls.push({url,options});return jsonResponse(200,{ok:true,duplicate:false,balance_after:MAX_ADJUSTMENT_AMOUNT});};const api=new SdAdminApi({baseUrl:BASE,publishableKey:KEY,fetchImpl});api.session={access_token:"token",refresh_token:"refresh"};const requestId="2c366c57-bdad-4bd5-b5a7-1be9db87d200";await api.adjustWallet({userId:"11111111-1111-1111-1111-111111111111",direction:"credit",amount:MAX_ADJUSTMENT_AMOUNT,note:"test",requestId});const body=JSON.parse(calls[0].options.body);assert.equal(body.p_request_id,requestId);assert.equal(body.p_amount,MAX_ADJUSTMENT_AMOUNT);assert.equal(body.p_direction,"credit");});
test("presence reporter uses one instance id across heartbeat and end",async()=>{const calls=[];const rpc=async(name,payload)=>{calls.push({name,payload});return{ok:true};};const reporter=new PresenceReporter({rpc,appId:"sd.center",appName:"SD종합센터",instanceId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",intervalMs:60000});await reporter.start();await reporter.stop();assert.equal(calls[0].name,"sd_presence_v1_heartbeat");assert.equal(calls[1].name,"sd_presence_v1_end");assert.equal(calls[0].payload.p_instance_id,calls[1].payload.p_instance_id);});
test("uncertain wallet request survives restart and successful same-ID retry clears journal",async()=>{const fs=require("fs"),os=require("os"),path=require("path");const {PendingAdjustmentStore}=require("../lib/pending-adjustment-store");const {WalletAdjustmentService}=require("../lib/wallet-adjustment-service");const dir=fs.mkdtempSync(path.join(os.tmpdir(),"sd-admin-journal-")),file=path.join(dir,"pending.json");const payload={userId:"u1",direction:"credit",amount:77,note:"test",requestId:"123e4567-e89b-42d3-a456-426614174000"};let attempt=0;const api={adjustWallet:async value=>{attempt+=1;assert.equal(value.requestId,payload.requestId);if(attempt===1){const error=new Error("response lost");error.uncertain=true;throw error;}return{ok:true,duplicate:true,balance_after:77};}};const service1=new WalletAdjustmentService({api,store:new PendingAdjustmentStore(file)});await assert.rejects(service1.adjust(payload));assert.equal(service1.pending().requestId,payload.requestId);const service2=new WalletAdjustmentService({api,store:new PendingAdjustmentStore(file)});assert.equal(service2.pending().requestId,payload.requestId);await service2.adjust(service2.pending());assert.equal(service2.pending(),null);fs.rmSync(dir,{recursive:true,force:true});});
