"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const {SdAdminApi,ApiError,normalizeBaseUrl,MAX_ADJUSTMENT_AMOUNT}=require("../lib/sd-admin-api");const {friendlyError}=require("../lib/errors");
const BASE="https://example.supabase.co",KEY="sb_publishable_abcdefghijklmnopqrstuvwxyz";function jsonResponse(status,body){return{ok:status>=200&&status<300,status,text:async()=>body==null?"":JSON.stringify(body)};}
test("non-HTTPS or non-Supabase endpoints are rejected",()=>{assert.throws(()=>normalizeBaseUrl("http://example.supabase.co"),/HTTPS_REQUIRED/);assert.throws(()=>normalizeBaseUrl("https://evil.example.com"),/INVALID_SUPABASE_HOST/);});
test("401 performs a single token refresh and retries the read",async()=>{const calls=[];const fetchImpl=async url=>{calls.push(url);if(url.includes("grant_type=refresh_token"))return jsonResponse(200,{access_token:"new-token",refresh_token:"new-refresh"});const rpcCalls=calls.filter(x=>x.includes("/rest/v1/rpc/")).length;if(rpcCalls===1)return jsonResponse(401,{message:"JWT expired"});return jsonResponse(200,[{user_id:"u"}]);};const api=new SdAdminApi({baseUrl:BASE,publishableKey:KEY,fetchImpl});api.session={access_token:"old",refresh_token:"refresh"};const data=await api.listUsers();assert.equal(data[0].user_id,"u");assert.equal(calls.filter(x=>x.includes("grant_type=refresh_token")).length,1);assert.equal(calls.filter(x=>x.includes("sd_admin_v1_list_users")).length,2);});
test("network loss during money mutation is marked uncertain for same-ID retry",async()=>{const fetchImpl=async()=>{throw new TypeError("socket closed");};const api=new SdAdminApi({baseUrl:BASE,publishableKey:KEY,fetchImpl});api.session={access_token:"token",refresh_token:"refresh"};await assert.rejects(api.adjustWallet({userId:"11111111-1111-1111-1111-111111111111",direction:"debit",amount:10,requestId:"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb"}),error=>error instanceof ApiError&&error.uncertain===true);});
test("invalid login credentials are shown as a specific safe message",async()=>{const api=new SdAdminApi({baseUrl:BASE,publishableKey:KEY,fetchImpl:async()=>jsonResponse(400,{code:"invalid_credentials",message:"Invalid login credentials"})});let caught=null;try{await api.signIn("admin@example.com","wrong");}catch(error){caught=error;}assert.ok(caught instanceof ApiError);assert.equal(api.isAuthenticated,false);assert.equal(friendlyError(caught),"이메일 또는 비밀번호가 올바르지 않습니다.");});
test("failed admin verification clears the freshly issued session",async()=>{let call=0;const fetchImpl=async url=>{call+=1;if(url.includes("/auth/v1/token"))return jsonResponse(200,{access_token:"token",refresh_token:"refresh",user:{}});return jsonResponse(403,{message:"ADMIN_REQUIRED"});};const api=new SdAdminApi({baseUrl:BASE,publishableKey:KEY,fetchImpl});await assert.rejects(api.signIn("admin@example.com","pw"));assert.equal(api.isAuthenticated,false);assert.equal(call,2);});
test("missing admin RPC after valid auth is reported as server-not-ready and session is cleared",async()=>{let call=0;const fetchImpl=async url=>{call+=1;if(url.includes("/auth/v1/token"))return jsonResponse(200,{access_token:"token",refresh_token:"refresh",user:{}});return jsonResponse(404,{code:"PGRST202",message:"Could not find the function public.sd_admin_v1_me in the schema cache"});};const api=new SdAdminApi({baseUrl:BASE,publishableKey:KEY,fetchImpl});let caught=null;try{await api.signIn("admin@example.com","pw");}catch(error){caught=error;}assert.ok(caught instanceof ApiError);assert.equal(api.isAuthenticated,false);assert.equal(call,2);assert.equal(friendlyError(caught),"관리자 서버 기능이 아직 준비되지 않았습니다.");});
test("client-side validation blocks zero, negative, decimal, over-1000억, and overlong-note adjustments before network",async()=>{let calls=0;const api=new SdAdminApi({baseUrl:BASE,publishableKey:KEY,fetchImpl:async()=>{calls+=1;return jsonResponse(200,{});}});api.session={access_token:"token",refresh_token:"refresh"};const common={userId:"11111111-1111-1111-1111-111111111111",direction:"credit",requestId:"cccccccc-cccc-4ccc-8ccc-cccccccccccc"};await assert.rejects(async()=>api.adjustWallet({...common,amount:0}),/INVALID_AMOUNT/);await assert.rejects(async()=>api.adjustWallet({...common,amount:-1}),/INVALID_AMOUNT/);await assert.rejects(async()=>api.adjustWallet({...common,amount:1.5}),/INVALID_AMOUNT/);await assert.rejects(async()=>api.adjustWallet({...common,amount:MAX_ADJUSTMENT_AMOUNT+1}),/INVALID_AMOUNT/);await assert.rejects(async()=>api.adjustWallet({...common,amount:1,note:"x".repeat(81)}),/NOTE_TOO_LONG/);assert.equal(calls,0);});
test("raw database and auth error codes are mapped to concise operator messages",()=>{assert.equal(friendlyError({message:"P1013: INSUFFICIENT_FUNDS"}),"잔액이 부족합니다.");assert.equal(friendlyError({message:"ADMIN_REQUIRED"}),"관리자 권한이 필요합니다.");assert.equal(friendlyError({message:"INVALID_AMOUNT"}),"금액은 1 이상 1,000억 이하의 정수로 입력하세요.");assert.equal(friendlyError({code:"PGRST202",message:"schema cache"}),"관리자 서버 기능이 아직 준비되지 않았습니다.");assert.equal(friendlyError({code:"invalid_credentials",message:"Invalid login credentials"}),"이메일 또는 비밀번호가 올바르지 않습니다.");assert.equal(friendlyError({status:500,message:"stack trace sql details"}),"서버 연결에 문제가 있습니다.");});
test("5xx during money mutation is also uncertain so the same request id is retained",async()=>{const api=new SdAdminApi({baseUrl:BASE,publishableKey:KEY,fetchImpl:async()=>jsonResponse(503,{message:"temporary upstream failure"})});api.session={access_token:"token",refresh_token:"refresh"};await assert.rejects(api.adjustWallet({userId:"11111111-1111-1111-1111-111111111111",direction:"credit",amount:10,requestId:"dddddddd-dddd-4ddd-8ddd-dddddddddddd"}),error=>error instanceof ApiError&&error.uncertain===true&&error.status===503);});
test("journal blocks a different wallet request while an uncertain request exists",()=>{const fs=require("fs"),os=require("os"),path=require("path");const {PendingAdjustmentStore}=require("../lib/pending-adjustment-store");const dir=fs.mkdtempSync(path.join(os.tmpdir(),"sd-admin-journal-conflict-"));const store=new PendingAdjustmentStore(path.join(dir,"pending.json"));store.save({userId:"u1",direction:"debit",amount:10,note:"a",requestId:"123e4567-e89b-42d3-a456-426614174001"});assert.throws(()=>store.save({userId:"u1",direction:"debit",amount:10,note:"a",requestId:"123e4567-e89b-42d3-a456-426614174002"}),/PENDING_ADJUSTMENT_EXISTS/);fs.rmSync(dir,{recursive:true,force:true});});
