"use strict";
window.SD_EXTENSION_PACKS = [
  {
    id: "sd-link",
    name: "SD Link",
    stage: "Stage 1",
    version: "v1.2.4",
    category: "온라인 연동 확장팩",
    icon: "assets/icons/center.png",
    fileName: "SDLink_v1.2.4_Desktop.zip",
    downloadUrl: "downloads/extensions/SDLink_v1.2.4_Desktop.zip",
    description: "센터 버전 증명과 필수 업데이트 서버 정책을 추가했습니다. 일반 회원의 구 센터 PC 거래는 서버에서 차단되며 관리자 계정은 예외입니다. v1.2.3 안정화와 동시수익 보호, BTC 정확 연동도 유지됩니다.",
    requirements: "SD종합센터 v2.1.1 이상 · SD지갑 · Windows 10/11",
    updatedAt: "2026-08-14",
    tags: ["응답없음 안정화", "동시 수익 보호", "BTC 정확 연동"],
    featured: true
  },
  {
    id: "sd-logistics-center",
    name: "SD 물류센터",
    stage: "Season 0",
    version: "v1.0.9",
    category: "경영 확장팩",
    icon: "assets/icons/logistics-center.png",
    fileName: "SDLogisticsCenter_Season0_Desktop.zip",
    downloadUrl: "downloads/extensions/SDLogisticsCenter_Season0_Desktop.zip?v=109",
    description: "SD지갑과 연동되는 물류회사 경영 확장팩입니다. v1.0.9 업데이트 후 물류 등급·실적·차량·기사·본부·계약 진행도를 계정/PC 기준으로 1회 초기화하며 SD지갑 잔액과 거래내역은 유지합니다. v1.0.8의 랭크 및 차량 해금 밸런스도 유지됩니다.",
    requirements: "SD종합센터 v2.1.2 이상 · SD지갑 · Windows 10/11",
    updatedAt: "2026-08-14",
    tags: ["SD지갑 유지", "1회 진행도 초기화", "랭크/차량 해금"],
    featured: true
  },
  {
    id: "sd-bitcoin-miner",
    name: "SD비트코인 채굴장",
    stage: "Version 1.2",
    version: "v1.2.2",
    category: "자동 수익 확장팩",
    icon: "assets/icons/bitcoin.png",
    fileName: "SDBitcoinMiner_v1.2.2_Desktop.zip",
    downloadUrl: "downloads/extensions/SDBitcoinMiner_v1.2.2_Desktop.zip?v=122",
    description: "v1.2.1에서 종합센터 확장팩 설치 경로의 공용 모듈 누락으로 실행되지 않던 문제를 수정했습니다. 채굴 확률 0.02%, GPU 155만원, GPU당 하루 전기세 10만원, 성공 시 해당 GPU 내구도 1% 감소 및 0% 파손 규칙을 유지합니다.",
    requirements: "SD종합센터 v2.1.3 이상 · SD지갑 · Windows 10/11",
    updatedAt: "2026-08-14",
    tags: ["실행 오류 수정", "GPU 내구도", "자동 업데이트"],
    featured: true
  },
  {
    id: "sd-slot",
    name: "SD슬롯",
    stage: "Stage 7",
    version: "v1.0.6",
    category: "게임 확장팩",
    icon: "assets/icons/slot.png",
    fileName: "SDSlot_Stage7_Desktop.zip",
    downloadUrl: "downloads/extensions/SDSlot_Stage7_Desktop.zip",
    description: "SD지갑 가상계좌와 연동되는 3릴 슬롯머신 시뮬레이션입니다. 선결제 후 3개 릴이 일치하면 가상 당첨금을 지급합니다.",
    requirements: "SD종합센터 v2.1.1 이상",
    updatedAt: "2026-07-31",
    tags: ["SD지갑 연동", "ZIP 앱 추가", "가상 시뮬레이션"],
    featured: true
  },
  {
    id: "sd-mukjippa",
    name: "SD묵찌빠",
    stage: "Version 1.1",
    version: "v1.0.1",
    category: "게임 확장팩",
    icon: "assets/icons/mukjippa.png",
    fileName: "SDMukjippa_Version1_1_Desktop.zip",
    downloadUrl: "downloads/extensions/SDMukjippa_Version1_1_Desktop.zip",
    description: "SD지갑 가상계좌와 연동되는 연승 도전형 묵찌빠 시뮬레이션입니다. 승리 후 보상을 정산하거나 다음 연승에 도전할 수 있습니다.",
    requirements: "SD종합센터 v2.1.1 이상",
    updatedAt: "2026-07-31",
    tags: ["SD지갑 연동", "연승 도전", "ZIP 앱 추가"],
    featured: true
  },
  {
    id: "sta",
    name: "STA",
    stage: "Version 6",
    version: "v1.5.1",
    category: "작전 확장팩",
    icon: "assets/icons/sta.png",
    fileName: "STA_Version6_Desktop.zip",
    downloadUrl: "downloads/extensions/STA_Version6_Desktop.zip?v=151",
    description: "해킹, 습격, 운반을 순서대로 수행하는 SD지갑 연동 작전 확장팩입니다. v1.5.1에서 현금 획득 종료 후 운반 화면으로 넘어가지 않던 버그를 수정했습니다.",
    requirements: "SD종합센터 v2.1.1 이상",
    updatedAt: "2026-08-14",
    tags: ["SD지갑 연동", "미니게임 3종", "ZIP 앱 추가"],
    featured: true
  },
  {
    id: "sd-flea-market",
    name: "SD 플리마켓",
    stage: "PC Expansion",
    version: "v1.0.0",
    category: "파밍·습격 확장팩",
    icon: "assets/icons/logistics-center.png",
    fileName: "SDFleaMarket_v1.0.0_Desktop.zip",
    downloadUrl: "#",
    unlockDownloadUrl: "downloads/extensions/SDFleaMarket_v1.0.0_Desktop.zip?v=100",
    description: "길거리·상가·물류센터 파밍과 상자 개봉, 은행 준비작업·피날레·오토바이 추격전을 담은 PC 확장팩입니다. 공식 확장팩 센터에서는 SD 물류회사 S등급에서 해금됩니다.",
    requirements: "SD종합센터 v2.2.0 이상 · SD 물류회사 S등급 · Windows 10/11",
    updatedAt: "2026-08-16",
    tags: ["S등급 해금", "은행 습격", "오토바이 추격"],
    featured: true,
    requiredLogisticsRank: "S",
    requiredLogisticsRep: 7000
  }
];
