create or replace function public.play_sd_slot(p_wager bigint,p_request_id uuid,p_platform text default 'android'::text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare
 v_user uuid:=auth.uid(); v_existing_user uuid; v_existing_result jsonb; v_status text; v_wallet uuid; v_roll integer; v_key text; v_name text; v_prob text; v_mult integer; v_payout bigint; v_won boolean; v_round uuid:=extensions.gen_random_uuid(); v_result jsonb; v_symbols text[]:=array['stone','coal','copper','iron','gold','emerald','diamond','seven','red-seven','gold-seven']; v_r1 text; v_r2 text; v_r3 text; v_i integer; v_wager_core jsonb; v_payout_core jsonb; v_before bigint; v_after_wager bigint; v_after bigint; v_platform text;
begin
 if v_user is null then raise exception '로그인이 필요합니다.'; end if; if p_request_id is null then raise exception '요청 번호가 없습니다.'; end if;
 v_platform:=lower(trim(coalesce(p_platform,'android'))); if v_platform not in ('windows','android','web') then raise exception '허용되지 않은 실행 환경입니다.'; end if; if p_wager is null or p_wager<100 or p_wager>1000000000 then raise exception '베팅금은 100원 이상 10억원 이하로 입력하세요.'; end if;
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(v_user::text||':slot:'||p_request_id::text,0));
 select user_id,result into v_existing_user,v_existing_result from public.game_rounds where request_id=p_request_id; if found then if v_existing_user<>v_user then raise exception '이미 사용된 요청 번호입니다.'; end if; return v_existing_result; end if;
 select p.status,w.id into v_status,v_wallet from public.profiles p join public.wallets w on w.user_id=p.id where p.id=v_user; if v_wallet is null then raise exception '가상지갑을 찾지 못했습니다.'; end if; if v_status<>'active' then raise exception '현재 이용할 수 없는 계정입니다.'; end if;
 v_roll:=public.sd_secure_random_int(100000)+1;
 if v_roll<=75000 then v_key:='miss';v_name:='꽝';v_mult:=0;v_prob:='75%'; elsif v_roll<=87000 then v_key:='stone';v_name:='돌';v_mult:=1;v_prob:='12%'; elsif v_roll<=93000 then v_key:='coal';v_name:='석탄';v_mult:=2;v_prob:='6%'; elsif v_roll<=96500 then v_key:='copper';v_name:='구리';v_mult:=3;v_prob:='3.5%'; elsif v_roll<=98500 then v_key:='iron';v_name:='철';v_mult:=5;v_prob:='2%'; elsif v_roll<=99500 then v_key:='gold';v_name:='금';v_mult:=10;v_prob:='1%'; elsif v_roll<=99850 then v_key:='emerald';v_name:='에메랄드';v_mult:=25;v_prob:='0.35%'; elsif v_roll<=99950 then v_key:='diamond';v_name:='다이아';v_mult:=50;v_prob:='0.1%'; elsif v_roll<=99990 then v_key:='seven';v_name:='7';v_mult:=100;v_prob:='0.04%'; elsif v_roll<=99999 then v_key:='red-seven';v_name:='빨간 7';v_mult:=250;v_prob:='0.009%'; else v_key:='gold-seven';v_name:='황금색 7';v_mult:=500;v_prob:='0.001%'; end if;
 v_won:=v_mult>0; v_payout:=p_wager*v_mult;
 if v_won then v_r1:=v_key;v_r2:=v_key;v_r3:=v_key; else v_r1:=v_symbols[public.sd_secure_random_int(array_length(v_symbols,1))+1];v_r2:=v_symbols[public.sd_secure_random_int(array_length(v_symbols,1))+1];v_r3:=v_symbols[public.sd_secure_random_int(array_length(v_symbols,1))+1]; if v_r1=v_r2 and v_r2=v_r3 then v_i:=array_position(v_symbols,v_r3);v_r3:=v_symbols[mod(v_i,array_length(v_symbols,1))+1]; end if; end if;
 v_wager_core:=sd_core_private.apply_server_wallet_delta_impl(v_user,p_request_id,'slot_wager',-p_wager,'sd_slot','SD슬롯 가상 베팅금',pg_catalog.jsonb_build_object('round_id',v_round,'roll',v_roll,'origin_platform',v_platform)); v_before:=(v_wager_core->>'balance_before')::bigint; v_after_wager:=(v_wager_core->>'balance_after')::bigint; v_after:=v_after_wager;
 if v_payout>0 then v_payout_core:=sd_core_private.apply_server_wallet_delta_impl(v_user,v_round,'slot_payout',v_payout,'sd_slot','SD슬롯 가상 당첨금 ('||v_name||' x'||v_mult||')',pg_catalog.jsonb_build_object('round_id',v_round,'result_key',v_key,'multiplier',v_mult,'origin_platform',v_platform)); v_after:=(v_payout_core->>'balance_after')::bigint; end if;
 v_result:=pg_catalog.jsonb_build_object('round_id',v_round,'game_type','slot','roll',v_roll,'result_key',v_key,'result_name',v_name,'probability',v_prob,'multiplier',v_mult,'reels',pg_catalog.jsonb_build_array(v_r1,v_r2,v_r3),'won',v_won,'jackpot',v_key='gold-seven','wager',p_wager,'payout',v_payout,'net',v_payout-p_wager,'balance_before',v_before,'balance_after',v_after,'rtp','75%','notice','실제 현금이 아닌 SD 게임용 가상화폐 결과입니다.');
 insert into public.game_rounds(id,user_id,wallet_id,game_type,wager,payout,result,status,request_id,platform,completed_at) values(v_round,v_user,v_wallet,'slot',p_wager,v_payout,v_result,'completed',p_request_id,v_platform,now());
 return v_result;
end$$;

create or replace function public.play_sd_odd_even(p_choice text,p_wager bigint,p_request_id uuid,p_platform text default 'android'::text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid(); v_existing_user uuid; v_existing_result jsonb; v_status text; v_wallet uuid; v_d1 integer; v_d2 integer; v_total integer; v_parity text; v_won boolean; v_payout bigint; v_round uuid:=extensions.gen_random_uuid(); v_result jsonb; v_wager_core jsonb; v_payout_core jsonb; v_before bigint; v_after_wager bigint; v_after bigint; v_platform text;
begin
 if v_user is null then raise exception '로그인이 필요합니다.'; end if; if p_request_id is null then raise exception '요청 번호가 없습니다.'; end if;
 p_choice:=lower(trim(coalesce(p_choice,''))); v_platform:=lower(trim(coalesce(p_platform,'android'))); if p_choice not in ('odd','even') then raise exception '홀 또는 짝을 선택하세요.'; end if; if v_platform not in ('windows','android','web') then raise exception '허용되지 않은 실행 환경입니다.'; end if; if p_wager is null or p_wager<100 or p_wager>1000000000 then raise exception '베팅금은 100원 이상 10억원 이하로 입력하세요.'; end if;
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(v_user::text||':odd-even:'||p_request_id::text,0));
 select user_id,result into v_existing_user,v_existing_result from public.game_rounds where request_id=p_request_id; if found then if v_existing_user<>v_user then raise exception '이미 사용된 요청 번호입니다.'; end if; return v_existing_result; end if;
 select p.status,w.id into v_status,v_wallet from public.profiles p join public.wallets w on w.user_id=p.id where p.id=v_user; if v_wallet is null then raise exception '가상지갑을 찾지 못했습니다.'; end if; if v_status<>'active' then raise exception '현재 이용할 수 없는 계정입니다.'; end if;
 v_d1:=public.sd_secure_random_int(6)+1;v_d2:=public.sd_secure_random_int(6)+1;v_total:=v_d1+v_d2;v_parity:=case when mod(v_total,2)=0 then 'even' else 'odd' end;v_won:=p_choice=v_parity;v_payout:=case when v_won then p_wager*2 else 0 end;
 v_wager_core:=sd_core_private.apply_server_wallet_delta_impl(v_user,p_request_id,'odd_even_wager',-p_wager,'sd_odd_even','SD홀짝 가상 베팅금',pg_catalog.jsonb_build_object('round_id',v_round,'choice',p_choice,'origin_platform',v_platform));v_before:=(v_wager_core->>'balance_before')::bigint;v_after_wager:=(v_wager_core->>'balance_after')::bigint;v_after:=v_after_wager;
 if v_payout>0 then v_payout_core:=sd_core_private.apply_server_wallet_delta_impl(v_user,v_round,'odd_even_payout',v_payout,'sd_odd_even','SD홀짝 가상 당첨금',pg_catalog.jsonb_build_object('round_id',v_round,'total',v_total,'parity',v_parity,'choice',p_choice,'origin_platform',v_platform));v_after:=(v_payout_core->>'balance_after')::bigint;end if;
 v_result:=pg_catalog.jsonb_build_object('round_id',v_round,'game_type','odd_even','choice',p_choice,'die1',v_d1,'die2',v_d2,'total',v_total,'parity',v_parity,'won',v_won,'wager',p_wager,'payout',v_payout,'net',v_payout-p_wager,'balance_before',v_before,'balance_after',v_after,'notice','실제 현금이 아닌 SD 게임용 가상화폐 결과입니다.');
 insert into public.game_rounds(id,user_id,wallet_id,game_type,wager,payout,result,status,request_id,platform,completed_at) values(v_round,v_user,v_wallet,'odd_even',p_wager,v_payout,v_result,'completed',p_request_id,v_platform,now());
 return v_result;
end$$;

create or replace function public.start_sd_odd_even(p_wager bigint,p_request_id uuid,p_platform text default 'android'::text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid(); v_status text; v_wallet uuid; v_d1 integer; v_d2 integer; v_round uuid:=extensions.gen_random_uuid(); v_existing public.sd_odd_even_sessions%rowtype; v_core jsonb; v_platform text; v_after bigint;
begin
 if v_user is null then raise exception '로그인이 필요합니다.'; end if;if p_request_id is null then raise exception '요청 번호가 없습니다.'; end if;v_platform:=lower(trim(coalesce(p_platform,'android')));if v_platform not in ('windows','android','web') then raise exception '허용되지 않은 실행 환경입니다.';end if;if p_wager is null or p_wager<100 or p_wager>1000000000 then raise exception '베팅금은 100원 이상 10억원 이하로 입력하세요.';end if;
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(v_user::text||':odd-even-start:'||p_request_id::text,0));
 select * into v_existing from public.sd_odd_even_sessions where request_id=p_request_id;if found then if v_existing.user_id<>v_user then raise exception '이미 사용된 요청 번호입니다.';end if;return pg_catalog.jsonb_build_object('round_id',v_existing.id,'status',v_existing.status,'wager',v_existing.wager,'balance_after_wager',v_existing.balance_after_wager,'expires_at',v_existing.expires_at);end if;
 update public.game_rounds set status='cancelled',completed_at=now() where user_id=v_user and game_type='odd_even' and status='pending' and id in(select id from public.sd_odd_even_sessions where user_id=v_user and status='pending' and expires_at<=now());update public.sd_odd_even_sessions set status='cancelled',completed_at=now() where user_id=v_user and status='pending' and expires_at<=now();if exists(select 1 from public.sd_odd_even_sessions where user_id=v_user and status='pending' and expires_at>now()) then raise exception '이미 결과 선택을 기다리는 홀짝 라운드가 있습니다.';end if;
 select p.status,w.id into v_status,v_wallet from public.profiles p join public.wallets w on w.user_id=p.id where p.id=v_user;if v_wallet is null then raise exception '가상지갑을 찾지 못했습니다.';end if;if v_status<>'active' then raise exception '현재 이용할 수 없는 계정입니다.';end if;
 v_d1:=public.sd_secure_random_int(6)+1;v_d2:=public.sd_secure_random_int(6)+1;v_core:=sd_core_private.apply_server_wallet_delta_impl(v_user,p_request_id,'odd_even_wager',-p_wager,'sd_odd_even','SD홀짝 가상 베팅금',pg_catalog.jsonb_build_object('round_id',v_round,'phase','dice_stopped','origin_platform',v_platform));v_after:=(v_core->>'balance_after')::bigint;
 insert into public.sd_odd_even_sessions(id,user_id,wallet_id,wager,die1,die2,request_id,platform,balance_after_wager) values(v_round,v_user,v_wallet,p_wager,v_d1,v_d2,p_request_id,v_platform,v_after);insert into public.game_rounds(id,user_id,wallet_id,game_type,wager,payout,result,status,request_id,platform) values(v_round,v_user,v_wallet,'odd_even',p_wager,0,pg_catalog.jsonb_build_object('phase','awaiting_choice'),'pending',p_request_id,v_platform);
 return pg_catalog.jsonb_build_object('round_id',v_round,'status','awaiting_choice','wager',p_wager,'balance_after_wager',v_after,'expires_at',now()+interval '5 minutes','message','주사위가 멈췄습니다. 홀 또는 짝을 선택하세요.');
end$$;

create or replace function public.finish_sd_odd_even(p_round_id uuid,p_choice text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid();v_s public.sd_odd_even_sessions%rowtype;v_total integer;v_parity text;v_won boolean;v_payout bigint;v_after bigint;v_result jsonb;v_core jsonb;
begin
 if v_user is null then raise exception '로그인이 필요합니다.';end if;p_choice:=lower(trim(coalesce(p_choice,'')));if p_choice not in ('odd','even') then raise exception '홀 또는 짝을 선택하세요.';end if;
 select * into v_s from public.sd_odd_even_sessions where id=p_round_id and user_id=v_user for update;if not found then raise exception '홀짝 라운드를 찾지 못했습니다.';end if;if v_s.status='completed' then return v_s.result;end if;if v_s.status<>'pending' then raise exception '이미 종료된 홀짝 라운드입니다.';end if;if v_s.expires_at<=now() then update public.sd_odd_even_sessions set status='cancelled',completed_at=now() where id=v_s.id;update public.game_rounds set status='cancelled',completed_at=now() where id=v_s.id;raise exception '선택 시간이 만료되었습니다.';end if;
 v_total:=v_s.die1+v_s.die2;v_parity:=case when mod(v_total,2)=0 then 'even' else 'odd' end;v_won:=p_choice=v_parity;v_payout:=case when v_won then v_s.wager*2 else 0 end;
 if v_payout>0 then v_core:=sd_core_private.apply_server_wallet_delta_impl(v_user,p_round_id,'odd_even_payout',v_payout,'sd_odd_even','SD홀짝 가상 당첨금',pg_catalog.jsonb_build_object('round_id',v_s.id,'total',v_total,'parity',v_parity,'choice',p_choice,'origin_platform',v_s.platform));v_after:=(v_core->>'balance_after')::bigint;else select balance into v_after from public.wallets where id=v_s.wallet_id;end if;
 v_result:=pg_catalog.jsonb_build_object('round_id',v_s.id,'game_type','odd_even','choice',p_choice,'die1',v_s.die1,'die2',v_s.die2,'total',v_total,'parity',v_parity,'won',v_won,'wager',v_s.wager,'payout',v_payout,'net',v_payout-v_s.wager,'balance_after',v_after,'notice','실제 현금이 아닌 SD 게임용 가상화폐 결과입니다.');
 update public.sd_odd_even_sessions set status='completed',choice=p_choice,result=v_result,completed_at=now() where id=v_s.id;update public.game_rounds set payout=v_payout,result=v_result,status='completed',completed_at=now() where id=v_s.id;return v_result;
end$$;

create or replace function public.start_npc_vault(p_difficulty text,p_request_id uuid,p_platform text default 'mobile'::text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid();v_today date:=(clock_timestamp() at time zone 'Asia/Seoul')::date;v_status text;v_wallet uuid;v_player public.npc_vault_players%rowtype;v_active uuid;v_existing uuid;v_diff text:=lower(trim(coalesce(p_difficulty,'')));v_platform text:=lower(coalesce(nullif(trim(p_platform),''),'mobile'));v_fee bigint;v_duration integer;v_min bigint;v_max bigint;v_run uuid;v_t1 smallint;v_t2 smallint;v_t3 smallint;v_core jsonb;
begin
 if v_user is null then raise exception '로그인이 필요합니다.';end if;if p_request_id is null then raise exception '게임 시작 요청 ID가 필요합니다.';end if;
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(v_user::text||':npc-start:'||p_request_id::text,0));
 select id into v_existing from public.npc_vault_runs where start_request_id=p_request_id and user_id=v_user;if v_existing is not null then return public.get_npc_vault_status();end if;perform public.get_npc_vault_status();
 select p.status,w.id into v_status,v_wallet from public.profiles p join public.wallets w on w.user_id=p.id where p.id=v_user;if v_wallet is null then raise exception '온라인 가상지갑을 찾지 못했습니다.';end if;if v_status<>'active' then raise exception '현재 이용할 수 없는 계정입니다.';end if;
 select * into v_player from public.npc_vault_players where user_id=v_user for update;if v_player.attempts_date<>v_today then update public.npc_vault_players set attempts_date=v_today,attempts_used=0,updated_at=now() where user_id=v_user returning * into v_player;end if;
 select id into v_active from public.npc_vault_runs where user_id=v_user and status='active' and expires_at>clock_timestamp() limit 1;if v_active is not null then raise exception '이미 진행 중인 NPC 금고가 있습니다.';end if;if v_player.cooldown_until is not null and v_player.cooldown_until>clock_timestamp() then raise exception '재도전 대기시간이 끝나지 않았습니다.';end if;if v_player.attempts_used>=5 then raise exception '오늘 도전 횟수 5회를 모두 사용했습니다.';end if;
 case v_diff when 'normal' then v_fee:=10000;v_duration:=35;v_min:=15000;v_max:=40000;when 'large' then v_fee:=50000;v_duration:=30;v_min:=80000;v_max:=200000;when 'mega' then v_fee:=200000;v_duration:=25;v_min:=350000;v_max:=1000000;else raise exception '올바른 금고 난이도를 선택하세요.';end case;
 v_t1:=public.sd_secure_random_int(100)+1;v_t2:=public.sd_secure_random_int(100)+1;v_t3:=public.sd_secure_random_int(100)+1;
 v_core:=sd_core_private.apply_server_wallet_delta_impl(v_user,p_request_id,'npc_vault_entry',-v_fee,'npc_vault',case v_diff when 'normal' then 'NPC 일반 금고 도전 참가비' when 'large' then 'NPC 대형 금고 도전 참가비' else 'NPC 초대형 금고 도전 참가비' end,pg_catalog.jsonb_build_object('difficulty',v_diff,'entry_fee',v_fee,'origin_platform',v_platform));
 update public.npc_vault_players set attempts_used=attempts_used+1,updated_at=now() where user_id=v_user;
 insert into public.npc_vault_runs(start_request_id,user_id,wallet_id,difficulty,entry_fee,duration_seconds,reward_min,reward_max,target_1,target_2,target_3,balance_before,balance_after_entry,platform,started_at,expires_at) values(p_request_id,v_user,v_wallet,v_diff,v_fee,v_duration,v_min,v_max,v_t1,v_t2,v_t3,(v_core->>'balance_before')::bigint,(v_core->>'balance_after')::bigint,v_platform,clock_timestamp(),clock_timestamp()+make_interval(secs=>v_duration)) returning id into v_run;
 return public.get_npc_vault_status();
end$$;

create or replace function public.finish_npc_vault(p_run_id uuid,p_numbers integer[],p_request_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid();v_run public.npc_vault_runs%rowtype;v_player public.npc_vault_players%rowtype;g1 integer;g2 integer;g3 integer;v_success boolean:=false;v_reward bigint:=0;v_after bigint;v_cool timestamptz;v_core jsonb;
begin
 if v_user is null then raise exception '로그인이 필요합니다.';end if;if p_run_id is null or p_request_id is null then raise exception '게임 완료 요청 정보가 필요합니다.';end if;
 select * into v_run from public.npc_vault_runs where id=p_run_id and user_id=v_user for update;if v_run.id is null then raise exception '진행 중인 NPC 금고를 찾지 못했습니다.';end if;if v_run.status<>'active' then return pg_catalog.jsonb_build_object('ok',true,'duplicate',true,'success',v_run.status='success','status',v_run.status,'reward',v_run.reward,'entry_fee',v_run.entry_fee,'net_result',v_run.reward-v_run.entry_fee,'balance_after',coalesce(v_run.balance_after_result,v_run.balance_after_entry),'completed_at',v_run.completed_at);end if;
 select * into v_player from public.npc_vault_players where user_id=v_user for update;if coalesce(array_length(p_numbers,1),0)>=1 then g1:=p_numbers[1];end if;if coalesce(array_length(p_numbers,1),0)>=2 then g2:=p_numbers[2];end if;if coalesce(array_length(p_numbers,1),0)>=3 then g3:=p_numbers[3];end if;
 if clock_timestamp()<=v_run.expires_at and coalesce(array_length(p_numbers,1),0)=3 and g1 between 1 and 100 and g2 between 1 and 100 and g3 between 1 and 100 and g1=v_run.target_1 and g2=v_run.target_2 and g3=v_run.target_3 then v_success:=true;end if;
 if v_success then v_reward:=(public.sd_secure_random_int((v_run.reward_max-v_run.reward_min+1)::integer)+v_run.reward_min)::bigint;v_cool:=clock_timestamp()+interval '10 minutes';v_core:=sd_core_private.apply_server_wallet_delta_impl(v_user,v_run.id,'npc_vault_reward',v_reward,'npc_vault',case v_run.difficulty when 'normal' then 'NPC 일반 금고 개방 보상' when 'large' then 'NPC 대형 금고 개방 보상' else 'NPC 초대형 금고 개방 보상' end,pg_catalog.jsonb_build_object('npc_vault_run_id',v_run.id,'difficulty',v_run.difficulty,'entry_fee',v_run.entry_fee,'finish_request_id',p_request_id,'origin_platform',v_run.platform));v_after:=(v_core->>'balance_after')::bigint;else select balance into v_after from public.wallets where id=v_run.wallet_id;v_cool:=clock_timestamp()+interval '5 minutes';end if;
 update public.npc_vault_runs set finish_request_id=p_request_id,guess_1=case when g1 between 1 and 100 then g1 else null end,guess_2=case when g2 between 1 and 100 then g2 else null end,guess_3=case when g3 between 1 and 100 then g3 else null end,status=case when v_success then 'success' else 'failed' end,reward=v_reward,balance_after_result=v_after,completed_at=clock_timestamp() where id=v_run.id;
 update public.npc_vault_players set cooldown_until=v_cool,updated_at=now() where user_id=v_user;
 return pg_catalog.jsonb_build_object('ok',true,'duplicate',false,'success',v_success,'status',case when v_success then 'success' else 'failed' end,'reward',v_reward,'entry_fee',v_run.entry_fee,'net_result',v_reward-v_run.entry_fee,'balance_after',v_after,'cooldown_until',v_cool,'cooldown_seconds',case when v_success then 600 else 300 end,'guesses',pg_catalog.jsonb_build_array(g1,g2,g3));
end$$;